/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockErc20Sol from "./MockERC20.sol";
export { UniswapInterfaceMulticall__factory } from "./UniswapInterfaceMulticall__factory";
